package kr.co.cobot.entity;
// Generated 2017. 6. 5 ���� 2:50:00 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbAn1Id generated by hbm2java 
 */
@Embeddable
public class TbAn1Id  implements java.io.Serializable {


     private Date srchDttm;
     private String ccd;

    public TbAn1Id() {
    }

    public TbAn1Id(Date srchDttm, String ccd) {
       this.srchDttm = srchDttm;
       this.ccd = ccd;
    }
   


    @Column(name="SRCH_DTTM", nullable=false, length=19)
    public Date getSrchDttm() {
        return this.srchDttm;
    }
    
    public void setSrchDttm(Date srchDttm) {
        this.srchDttm = srchDttm;
    }


    @Column(name="CCD", nullable=false, length=5)
    public String getCcd() {
        return this.ccd;
    }
    
    public void setCcd(String ccd) {
        this.ccd = ccd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbAn1Id) ) return false;
		 TbAn1Id castOther = ( TbAn1Id ) other; 
         
		 return ( (this.getSrchDttm()==castOther.getSrchDttm()) || ( this.getSrchDttm()!=null && castOther.getSrchDttm()!=null && this.getSrchDttm().equals(castOther.getSrchDttm()) ) )
 && ( (this.getCcd()==castOther.getCcd()) || ( this.getCcd()!=null && castOther.getCcd()!=null && this.getCcd().equals(castOther.getCcd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSrchDttm() == null ? 0 : this.getSrchDttm().hashCode() );
         result = 37 * result + ( getCcd() == null ? 0 : this.getCcd().hashCode() );
         return result;
   }   


}


