package kr.co.cobot.entity;
// Generated 2017. 7. 19 ���� 1:12:19 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbBuyReq generated by hbm2java
 */
@Entity
@Table(name = "tb_buy_req", catalog = "cobot")
public class TbBuyReq implements java.io.Serializable {

	private TbBuyReqId id;

	public TbBuyReq() {
	}

	public TbBuyReq(TbBuyReqId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "USER_ID", length = 20)),
			@AttributeOverride(name = "eid", column = @Column(name = "EID")),
			@AttributeOverride(name = "cid", column = @Column(name = "CID")),
			@AttributeOverride(name = "ccd", column = @Column(name = "CCD", length = 5)),
			@AttributeOverride(name = "purPrice", column = @Column(name = "PUR_PRICE", length = 5)),
			@AttributeOverride(name = "purAmount", column = @Column(name = "PUR_AMOUNT", length = 5)),
			@AttributeOverride(name = "reqDttm", column = @Column(name = "REQ_DTTM", length = 19)),
			@AttributeOverride(name = "regDttm", column = @Column(name = "REG_DTTM", length = 19)),
			@AttributeOverride(name = "modDttm", column = @Column(name = "MOD_DTTM", length = 19)) })
	public TbBuyReqId getId() {
		return this.id;
	}

	public void setId(TbBuyReqId id) {
		this.id = id;
	}

}
