package kr.co.cobot.entity;
// Generated 2017. 8. 5 ���� 10:22:22 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbCacheImg generated by hbm2java 
 */
@Entity
@Table(name = "tb_cache_img", catalog = "cobot")
public class TbCacheImg implements java.io.Serializable {

	private Integer id;
	private String imgUrl;
	private String imgPath;

	public TbCacheImg() {
	}

	public TbCacheImg(String imgUrl, String imgPath) {
		this.imgUrl = imgUrl;
		this.imgPath = imgPath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "imgUrl", nullable = false, length = 2048)
	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	@Column(name = "imgPath", nullable = false, length = 128)
	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
