package kr.co.cobot.entity;
// Generated 2017. 7. 11 ���� 1:11:18 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbCoSnapId generated by hbm2java
 */
@Embeddable
public class TbCoSnapId implements java.io.Serializable {

	private Date srchDttm;
	private int eid;
	private int unitCid; 
	private int cid;

	public TbCoSnapId() {
	}

	public TbCoSnapId(Date srchDttm, int eid, int unitCid, int cid) {
		this.srchDttm = srchDttm;
		this.eid = eid;
		this.unitCid = unitCid;
		this.cid = cid;
	}

	@Column(name = "SRCH_DTTM", nullable = false, length = 19)
	public Date getSrchDttm() {
		return this.srchDttm;
	}

	public void setSrchDttm(Date srchDttm) {
		this.srchDttm = srchDttm;
	}

	@Column(name = "EID", nullable = false)
	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	@Column(name = "UNIT_CID", nullable = false)
	public int getUnitCid() {
		return this.unitCid;
	}

	public void setUnitCid(int unitCid) {
		this.unitCid = unitCid;
	}

	@Column(name = "CID", nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbCoSnapId))
			return false;
		TbCoSnapId castOther = (TbCoSnapId) other;

		return ((this.getSrchDttm() == castOther.getSrchDttm()) || (this.getSrchDttm() != null
				&& castOther.getSrchDttm() != null && this.getSrchDttm().equals(castOther.getSrchDttm())))
				&& (this.getEid() == castOther.getEid()) && (this.getUnitCid() == castOther.getUnitCid())
				&& (this.getCid() == castOther.getCid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSrchDttm() == null ? 0 : this.getSrchDttm().hashCode());
		result = 37 * result + this.getEid();
		result = 37 * result + this.getUnitCid();
		result = 37 * result + this.getCid();
		return result;
	}

}
