package kr.co.cobot.entity;
// Generated 2017. 6. 5 ���� 2:50:00 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbExchCoId generated by hbm2java 
 */
@Embeddable
public class TbExchCoId implements java.io.Serializable {

	private int eid;
	private int cid;

	public TbExchCoId() {
	}

	public TbExchCoId(int eid, int cid) {
		this.eid = eid;
		this.cid = cid;
	}

	@Column(name = "EID", nullable = false)
	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	@Column(name = "CID", nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbExchCoId))
			return false;
		TbExchCoId castOther = (TbExchCoId) other;

		return (this.getEid() == castOther.getEid()) && (this.getCid() == castOther.getCid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEid();
		result = 37 * result + this.getCid();
		return result;
	}

}
