package kr.co.cobot.entity;
// Generated 2017. 6. 5 ���� 2:50:00 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbExchCo generated by hbm2java
 */
@Entity
@Table(name = "tb_exch_co", catalog = "cobot")
public class TbExchCo implements java.io.Serializable {

	private TbExchCoId id;
	private String ccd;
	private String cnm;
	private String cnmKo;
	private Date regDttm;
	private Date modDttm;

	public TbExchCo() {
	}

	public TbExchCo(TbExchCoId id) {
		this.id = id;
	}

	public TbExchCo(TbExchCoId id, String ccd, String cnm, String cnmKo, Date regDttm, Date modDttm) {
		this.id = id;
		this.ccd = ccd;
		this.cnm = cnm;
		this.cnmKo = cnmKo;
		this.regDttm = regDttm;
		this.modDttm = modDttm;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "eid", column = @Column(name = "EID", nullable = false)),
			@AttributeOverride(name = "cid", column = @Column(name = "CID", nullable = false)) })
	public TbExchCoId getId() {
		return this.id;
	}

	public void setId(TbExchCoId id) {
		this.id = id;
	}

	@Column(name = "CCD", length = 5)
	public String getCcd() {
		return this.ccd;
	}

	public void setCcd(String ccd) {
		this.ccd = ccd;
	}

	@Column(name = "CNM", length = 50)
	public String getCnm() {
		return this.cnm;
	}

	public void setCnm(String cnm) {
		this.cnm = cnm;
	}

	@Column(name = "CNM_KO", length = 100)
	public String getCnmKo() {
		return this.cnmKo;
	}

	public void setCnmKo(String cnmKo) {
		this.cnmKo = cnmKo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REG_DTTM", length = 19)
	public Date getRegDttm() {
		return this.regDttm;
	}

	public void setRegDttm(Date regDttm) {
		this.regDttm = regDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MOD_DTTM", length = 19)
	public Date getModDttm() {
		return this.modDttm;
	}

	public void setModDttm(Date modDttm) {
		this.modDttm = modDttm;
	}

}
