package kr.co.cobot.entity;
// Generated 2017. 7. 19 ���� 1:12:19 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPostInfo generated by hbm2java 
 */
@Entity
@Table(name="tb_post_info"
    ,catalog="cobot"
)
public class TbPostInfo  implements java.io.Serializable {


     private Integer postId;
     private String siteDvcd;
     private String categoryDvcd;
     private String postDvcd;
     private String arrTagStr;
     private String postAuthor;
     private String postUrl;
     private String postTitle;
     private String postBody;
     private String postImgUrl;
     private Date regDttm;
     private Date modDttm;

    public TbPostInfo() {
    }

	
    public TbPostInfo(String siteDvcd, String categoryDvcd, String postDvcd, String postUrl, String postTitle) {
        this.siteDvcd = siteDvcd;
        this.categoryDvcd = categoryDvcd;
        this.postDvcd = postDvcd;
        this.postUrl = postUrl;
        this.postTitle = postTitle;
    }
    public TbPostInfo(String siteDvcd, String categoryDvcd, String postDvcd, String arrTagStr, String postAuthor, String postUrl, String postTitle, String postBody, String postImgUrl, Date regDttm, Date modDttm) {
       this.siteDvcd = siteDvcd;
       this.categoryDvcd = categoryDvcd;
       this.postDvcd = postDvcd;
       this.arrTagStr = arrTagStr;
       this.postAuthor = postAuthor;
       this.postUrl = postUrl;
       this.postTitle = postTitle;
       this.postBody = postBody;
       this.postImgUrl = postImgUrl;
       this.regDttm = regDttm;
       this.modDttm = modDttm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="POST_ID", unique=true, nullable=false)
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    
    @Column(name="SITE_DVCD", nullable=false, length=20)
    public String getSiteDvcd() {
        return this.siteDvcd;
    }
    
    public void setSiteDvcd(String siteDvcd) {
        this.siteDvcd = siteDvcd;
    }

    
    @Column(name="CATEGORY_DVCD", nullable=false, length=20)
    public String getCategoryDvcd() {
        return this.categoryDvcd;
    }
    
    public void setCategoryDvcd(String categoryDvcd) {
        this.categoryDvcd = categoryDvcd;
    }

    
    @Column(name="POST_DVCD", nullable=false, length=20)
    public String getPostDvcd() {
        return this.postDvcd;
    }
    
    public void setPostDvcd(String postDvcd) {
        this.postDvcd = postDvcd;
    }

    
    @Column(name="ARR_TAG_STR", length=128)
    public String getArrTagStr() {
        return this.arrTagStr;
    }
    
    public void setArrTagStr(String arrTagStr) {
        this.arrTagStr = arrTagStr;
    }

    
    @Column(name="POST_AUTHOR", length=64)
    public String getPostAuthor() {
        return this.postAuthor;
    }
    
    public void setPostAuthor(String postAuthor) {
        this.postAuthor = postAuthor;
    }

    
    @Column(name="POST_URL", nullable=false, length=256)
    public String getPostUrl() {
        return this.postUrl;
    }
    
    public void setPostUrl(String postUrl) {
        this.postUrl = postUrl;
    }

    
    @Column(name="POST_TITLE", nullable=false, length=256)
    public String getPostTitle() {
        return this.postTitle;
    }
    
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    
    @Column(name="POST_BODY", length=1024)
    public String getPostBody() {
        return this.postBody;
    }
    
    public void setPostBody(String postBody) {
        this.postBody = postBody;
    }

    
    @Column(name="POST_IMG_URL", length=512)
    public String getPostImgUrl() {
        return this.postImgUrl;
    }
    
    public void setPostImgUrl(String postImgUrl) {
        this.postImgUrl = postImgUrl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REG_DTTM", length=19)
    public Date getRegDttm() {
        return this.regDttm;
    }
    
    public void setRegDttm(Date regDttm) {
        this.regDttm = regDttm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DTTM", length=19)
    public Date getModDttm() {
        return this.modDttm;
    }
    
    public void setModDttm(Date modDttm) {
        this.modDttm = modDttm;
    }




}


