package kr.co.cobot.entity;
// Generated 2017. 8. 2 ���� 11:22:20 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbPostMarketReplyId generated by hbm2java 
 */
@Embeddable
public class TbPostMarketReplyId implements java.io.Serializable {

	private Long replyId;
	private int postId;
	private String author;
	private Double auctionAmt;
	private Date replyRegDttm;
	private String comment;
	private Date regDttm;
	private Date modDttm;

	public TbPostMarketReplyId() {
	}

	public TbPostMarketReplyId(int postId, Date replyRegDttm, Date regDttm, Date modDttm) {
		this.postId = postId;
		this.replyRegDttm = replyRegDttm;
		this.regDttm = regDttm;
		this.modDttm = modDttm;
	}

	public TbPostMarketReplyId(Long replyId, int postId, String author, Double auctionAmt, Date replyRegDttm,
			String comment, Date regDttm, Date modDttm) {
		this.replyId = replyId;
		this.postId = postId;
		this.author = author;
		this.auctionAmt = auctionAmt;
		this.replyRegDttm = replyRegDttm;
		this.comment = comment;
		this.regDttm = regDttm;
		this.modDttm = modDttm;
	}

	@Column(name = "REPLY_ID")
	public Long getReplyId() {
		return this.replyId;
	}

	public void setReplyId(Long replyId) {
		this.replyId = replyId;
	}

	@Column(name = "POST_ID", nullable = false)
	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	@Column(name = "AUTHOR", length = 64)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "AUCTION_AMT", precision = 22, scale = 0)
	public Double getAuctionAmt() {
		return this.auctionAmt;
	}

	public void setAuctionAmt(Double auctionAmt) {
		this.auctionAmt = auctionAmt;
	}

	@Column(name = "REPLY_REG_DTTM", nullable = false, length = 19)
	public Date getReplyRegDttm() {
		return this.replyRegDttm;
	}

	public void setReplyRegDttm(Date replyRegDttm) {
		this.replyRegDttm = replyRegDttm;
	}

	@Column(name = "COMMENT", length = 2048)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "REG_DTTM", nullable = false, length = 19)
	public Date getRegDttm() {
		return this.regDttm;
	}

	public void setRegDttm(Date regDttm) {
		this.regDttm = regDttm;
	}

	@Column(name = "MOD_DTTM", nullable = false, length = 19)
	public Date getModDttm() {
		return this.modDttm;
	}

	public void setModDttm(Date modDttm) {
		this.modDttm = modDttm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbPostMarketReplyId))
			return false;
		TbPostMarketReplyId castOther = (TbPostMarketReplyId) other;

		return ((this.getReplyId() == castOther.getReplyId()) || (this.getReplyId() != null
				&& castOther.getReplyId() != null && this.getReplyId().equals(castOther.getReplyId())))
				&& (this.getPostId() == castOther.getPostId())
				&& ((this.getAuthor() == castOther.getAuthor()) || (this.getAuthor() != null
						&& castOther.getAuthor() != null && this.getAuthor().equals(castOther.getAuthor())))
				&& ((this.getAuctionAmt() == castOther.getAuctionAmt()) || (this.getAuctionAmt() != null
						&& castOther.getAuctionAmt() != null && this.getAuctionAmt().equals(castOther.getAuctionAmt())))
				&& ((this.getReplyRegDttm() == castOther.getReplyRegDttm())
						|| (this.getReplyRegDttm() != null && castOther.getReplyRegDttm() != null
								&& this.getReplyRegDttm().equals(castOther.getReplyRegDttm())))
				&& ((this.getComment() == castOther.getComment()) || (this.getComment() != null
						&& castOther.getComment() != null && this.getComment().equals(castOther.getComment())))
				&& ((this.getRegDttm() == castOther.getRegDttm()) || (this.getRegDttm() != null
						&& castOther.getRegDttm() != null && this.getRegDttm().equals(castOther.getRegDttm())))
				&& ((this.getModDttm() == castOther.getModDttm()) || (this.getModDttm() != null
						&& castOther.getModDttm() != null && this.getModDttm().equals(castOther.getModDttm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getReplyId() == null ? 0 : this.getReplyId().hashCode());
		result = 37 * result + this.getPostId();
		result = 37 * result + (getAuthor() == null ? 0 : this.getAuthor().hashCode());
		result = 37 * result + (getAuctionAmt() == null ? 0 : this.getAuctionAmt().hashCode());
		result = 37 * result + (getReplyRegDttm() == null ? 0 : this.getReplyRegDttm().hashCode());
		result = 37 * result + (getComment() == null ? 0 : this.getComment().hashCode());
		result = 37 * result + (getRegDttm() == null ? 0 : this.getRegDttm().hashCode());
		result = 37 * result + (getModDttm() == null ? 0 : this.getModDttm().hashCode());
		return result;
	}

}
