package kr.co.cobot.entity;
// Generated 2017. 8. 5 ���� 10:22:22 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPostMarketReply generated by hbm2java 
 */
@Entity
@Table(name = "tb_post_market_reply", catalog = "cobot")
public class TbPostMarketReply implements java.io.Serializable {

	private long replyId;
	private int postId;
	private String author;
	private Double auctionAmt;
	private Date replyRegDttm;
	private String comment;
	private Date regDttm;
	private Date modDttm;

	public TbPostMarketReply() {
	}

	public TbPostMarketReply(long replyId, int postId, Date replyRegDttm) {
		this.replyId = replyId;
		this.postId = postId;
		this.replyRegDttm = replyRegDttm;
	}

	public TbPostMarketReply(long replyId, int postId, String author, Double auctionAmt, Date replyRegDttm,
			String comment, Date regDttm, Date modDttm) {
		this.replyId = replyId;
		this.postId = postId;
		this.author = author;
		this.auctionAmt = auctionAmt;
		this.replyRegDttm = replyRegDttm;
		this.comment = comment;
		this.regDttm = regDttm;
		this.modDttm = modDttm;
	}

	@Id

	@Column(name = "REPLY_ID", unique = true, nullable = false)
	public long getReplyId() {
		return this.replyId;
	}

	public void setReplyId(long replyId) {
		this.replyId = replyId;
	}

	@Column(name = "POST_ID", nullable = false)
	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	@Column(name = "AUTHOR", length = 64)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "AUCTION_AMT", precision = 22, scale = 0)
	public Double getAuctionAmt() {
		return this.auctionAmt;
	}

	public void setAuctionAmt(Double auctionAmt) {
		this.auctionAmt = auctionAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REPLY_REG_DTTM", nullable = false, length = 19)
	public Date getReplyRegDttm() {
		return this.replyRegDttm;
	}

	public void setReplyRegDttm(Date replyRegDttm) {
		this.replyRegDttm = replyRegDttm;
	}

	@Column(name = "COMMENT", length = 2048)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REG_DTTM", length = 19)
	public Date getRegDttm() {
		return this.regDttm;
	}

	public void setRegDttm(Date regDttm) {
		this.regDttm = regDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MOD_DTTM", length = 19)
	public Date getModDttm() {
		return this.modDttm;
	}

	public void setModDttm(Date modDttm) {
		this.modDttm = modDttm;
	}

}
