package kr.co.cobot.entity;
// Generated 2017. 7. 11 ���� 1:11:18 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/** 
 * TbWebPushPost generated by hbm2java
 */
@Entity
@Table(name="tb_web_push_post"
    ,catalog="cobot"
)
public class TbWebPushPost  implements java.io.Serializable {


     private TbWebPushPostId id;
     private String postTitle;
     private String postImgUrl;
     private Date regDttm;
     private Date modDttm;

    public TbWebPushPost() {
    }

	
    public TbWebPushPost(TbWebPushPostId id, String postTitle, String postImgUrl) {
        this.id = id;
        this.postTitle = postTitle;
        this.postImgUrl = postImgUrl;
    }
    public TbWebPushPost(TbWebPushPostId id, String postTitle, String postImgUrl, Date regDttm, Date modDttm) {
       this.id = id;
       this.postTitle = postTitle;
       this.postImgUrl = postImgUrl;
       this.regDttm = regDttm;
       this.modDttm = modDttm;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="siteDvcd", column=@Column(name="SITE_DVCD", nullable=false, length=20) ), 
        @AttributeOverride(name="categoryDvcd", column=@Column(name="CATEGORY_DVCD", nullable=false, length=20) ), 
        @AttributeOverride(name="postDvcd", column=@Column(name="POST_DVCD", nullable=false, length=20) ), 
        @AttributeOverride(name="tagDvcd", column=@Column(name="TAG_DVCD", nullable=false, length=20) ), 
        @AttributeOverride(name="postUrl", column=@Column(name="POST_URL", nullable=false, length=96) ) } )
    public TbWebPushPostId getId() {
        return this.id;
    }
    
    public void setId(TbWebPushPostId id) {
        this.id = id;
    }

    
    @Column(name="POST_TITLE", nullable=false, length=256)
    public String getPostTitle() {
        return this.postTitle;
    }
    
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    
    @Column(name="POST_IMG_URL", nullable=false, length=256)
    public String getPostImgUrl() {
        return this.postImgUrl;
    }
    
    public void setPostImgUrl(String postImgUrl) {
        this.postImgUrl = postImgUrl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REG_DTTM", length=19)
    public Date getRegDttm() {
        return this.regDttm;
    }
    
    public void setRegDttm(Date regDttm) {
        this.regDttm = regDttm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DTTM", length=19)
    public Date getModDttm() {
        return this.modDttm;
    }
    
    public void setModDttm(Date modDttm) {
        this.modDttm = modDttm;
    }




}


