package kr.co.cobot.entity;
// Generated 2017. 7. 19 ���� 1:12:19 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/** 
 * TbWebPushM generated by hbm2java
 */
@Entity
@Table(name="tb_web_push_m"
    ,catalog="cobot"
)
public class TbWebPushM  implements java.io.Serializable {


     private String alarmId;
     private Short webDvcd;
     private String endPoint;
     private String publicKey;
     private String auth;
     private String steemDvcd;
     private String alarmSettingStr;
     private Date regDttm;
     private Date modDttm;

    public TbWebPushM() {
    }

	
    public TbWebPushM(String alarmId) {
        this.alarmId = alarmId;
    }
    public TbWebPushM(String alarmId, Short webDvcd, String endPoint, String publicKey, String auth, String steemDvcd, String alarmSettingStr, Date regDttm, Date modDttm) {
       this.alarmId = alarmId;
       this.webDvcd = webDvcd;
       this.endPoint = endPoint;
       this.publicKey = publicKey;
       this.auth = auth;
       this.steemDvcd = steemDvcd;
       this.alarmSettingStr = alarmSettingStr;
       this.regDttm = regDttm;
       this.modDttm = modDttm;
    }
   
     @Id 

    
    @Column(name="ALARM_ID", unique=true, nullable=false, length=64)
    public String getAlarmId() {
        return this.alarmId;
    }
    
    public void setAlarmId(String alarmId) {
        this.alarmId = alarmId;
    }

    
    @Column(name="WEB_DVCD")
    public Short getWebDvcd() {
        return this.webDvcd;
    }
    
    public void setWebDvcd(Short webDvcd) {
        this.webDvcd = webDvcd;
    }

    
    @Column(name="END_POINT", length=256)
    public String getEndPoint() {
        return this.endPoint;
    }
    
    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint;
    }

    
    @Column(name="PUBLIC_KEY", length=256)
    public String getPublicKey() {
        return this.publicKey;
    }
    
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    
    @Column(name="AUTH", length=256)
    public String getAuth() {
        return this.auth;
    }
    
    public void setAuth(String auth) {
        this.auth = auth;
    }

    
    @Column(name="STEEM_DVCD", length=32)
    public String getSteemDvcd() {
        return this.steemDvcd;
    }
    
    public void setSteemDvcd(String steemDvcd) {
        this.steemDvcd = steemDvcd;
    }

    
    @Column(name="ALARM_SETTING_STR", length=1024)
    public String getAlarmSettingStr() {
        return this.alarmSettingStr;
    }
    
    public void setAlarmSettingStr(String alarmSettingStr) {
        this.alarmSettingStr = alarmSettingStr;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REG_DTTM", length=19)
    public Date getRegDttm() {
        return this.regDttm;
    }
    
    public void setRegDttm(Date regDttm) {
        this.regDttm = regDttm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DTTM", length=19)
    public Date getModDttm() {
        return this.modDttm;
    }
    
    public void setModDttm(Date modDttm) {
        this.modDttm = modDttm;
    }




}


