package kr.co.cobot.entity;
// Generated 2017. 7. 11 ���� 1:11:18 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/** 
 * TbWebPushPostId generated by hbm2java
 */
@Embeddable
public class TbWebPushPostId implements java.io.Serializable {

	private String siteDvcd;
	private String categoryDvcd;
	private String postDvcd;
	private String tagDvcd;
	private String postUrl;

	public TbWebPushPostId() {
	}

	public TbWebPushPostId(String siteDvcd, String categoryDvcd, String postDvcd, String tagDvcd, String postUrl) {
		this.siteDvcd = siteDvcd;
		this.categoryDvcd = categoryDvcd;
		this.postDvcd = postDvcd;
		this.tagDvcd = tagDvcd;
		this.postUrl = postUrl;
	}

	@Column(name = "SITE_DVCD", nullable = false, length = 20)
	public String getSiteDvcd() {
		return this.siteDvcd;
	}

	public void setSiteDvcd(String siteDvcd) {
		this.siteDvcd = siteDvcd;
	}

	@Column(name = "CATEGORY_DVCD", nullable = false, length = 20)
	public String getCategoryDvcd() {
		return this.categoryDvcd;
	}

	public void setCategoryDvcd(String categoryDvcd) {
		this.categoryDvcd = categoryDvcd;
	}

	@Column(name = "POST_DVCD", nullable = false, length = 20)
	public String getPostDvcd() {
		return this.postDvcd;
	}

	public void setPostDvcd(String postDvcd) {
		this.postDvcd = postDvcd;
	}

	@Column(name = "TAG_DVCD", nullable = false, length = 20)
	public String getTagDvcd() {
		return this.tagDvcd;
	}

	public void setTagDvcd(String tagDvcd) {
		this.tagDvcd = tagDvcd;
	}

	@Column(name = "POST_URL", nullable = false, length = 96)
	public String getPostUrl() {
		return this.postUrl;
	}

	public void setPostUrl(String postUrl) {
		this.postUrl = postUrl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbWebPushPostId))
			return false;
		TbWebPushPostId castOther = (TbWebPushPostId) other;

		return ((this.getSiteDvcd() == castOther.getSiteDvcd()) || (this.getSiteDvcd() != null
				&& castOther.getSiteDvcd() != null && this.getSiteDvcd().equals(castOther.getSiteDvcd())))
				&& ((this.getCategoryDvcd() == castOther.getCategoryDvcd())
						|| (this.getCategoryDvcd() != null && castOther.getCategoryDvcd() != null
								&& this.getCategoryDvcd().equals(castOther.getCategoryDvcd())))
				&& ((this.getPostDvcd() == castOther.getPostDvcd()) || (this.getPostDvcd() != null
						&& castOther.getPostDvcd() != null && this.getPostDvcd().equals(castOther.getPostDvcd())))
				&& ((this.getTagDvcd() == castOther.getTagDvcd()) || (this.getTagDvcd() != null
						&& castOther.getTagDvcd() != null && this.getTagDvcd().equals(castOther.getTagDvcd())))
				&& ((this.getPostUrl() == castOther.getPostUrl()) || (this.getPostUrl() != null
						&& castOther.getPostUrl() != null && this.getPostUrl().equals(castOther.getPostUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSiteDvcd() == null ? 0 : this.getSiteDvcd().hashCode());
		result = 37 * result + (getCategoryDvcd() == null ? 0 : this.getCategoryDvcd().hashCode());
		result = 37 * result + (getPostDvcd() == null ? 0 : this.getPostDvcd().hashCode());
		result = 37 * result + (getTagDvcd() == null ? 0 : this.getTagDvcd().hashCode());
		result = 37 * result + (getPostUrl() == null ? 0 : this.getPostUrl().hashCode());
		return result;
	}

}
